name: deploy-auth 
on: 
  push: 
    branches: 
    - master 
    paths: 
    - auth/** 
    
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2 
      - run: cd auth && docker build -t guilhermebiavati/auth .
      - run: docker login -u guilhermebiavati -p Docker1311#@
      - run: docker push guilhermebiavati/auth
