name: deploy-auth 
on: 
  push: 
    branches: 
    - master 
    paths: 
    - auth/** 
    
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@v2 
      - run: cd auth && docker build -t guilhermebiavati/auth .
      - run: docker push guilhermebiavati/auth
