name: deploy-auth 
on: 
  push: 
    branches: 
    - master 
    paths: 
    - auth/** 
    
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Check out the repo 
        uses: actions/checkout@v2 
      - run: cd auth && docker build -t guilhermebiavati/auth . 
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
      - run: docker push guilhermebiavati/auth
